# Changes here will be overwritten by Copier
_commit: v0.4.2
_src_path: https://github.com/linkml/linkml-project-copier
add_example: false
copyright_year: '2026'
email: francois.lanusse@cnrs.fr
full_name: Francois Lanusse
gh_action_docs_preview: true
gh_action_pypi: true
github_org: LightconeResearch
license: Apache-2.0
project_description: Agentic Schema for Transparent Research Analysis.
project_name: ASTRA
project_slug: astra-spec

